### ISSUE TITLE
Scrum Updates

### ISSUE THREAD

**Issue by KwanLam17** [siddhero97/CS436I-Memofy#4]
**User Story**

As an `Instructor or TA`,
I want to `be updated with what each member is working on/will work on`,
So that `I can gauge their individual contributions to the team`.

**Functional Requirements**

* Every member writes a scrum update "comment" below answering the following questions:
  * What did you work on last iteration?
  * What were any major issues/challenges you ran into?
  * What do you plan to work on for this coming iteration?
  * CSID

**Comment by vincentchiang1** [comment]
Discussed and planned our project task requirements, expectations. Created mock designs and prototypes of our application. Set expectations for future collaboration such as meeting times and standards of communication. A challenge was creating and agreeing on an optimal design that we can implement. Plan to work on pinpointing UI together and then begin implementing the front-end.

**Comment by KwanLam17** [comment]
* What did you work on last iteration?

Discussed and planned our project task requirements, expectations. Created mock designs and prototypes of our application. Set expectations for future collaboration such as meeting times and standards of communication.

* What were any major issues/challenges you ran into?

Creating and agreeing on an optimal design that we can implement. Still an ongoing issue to come up with better designs.

* What do you plan to work on for this coming iteration?

Come up with a better design (probably through figma) and begin coming up with and breaking up frontend tasks to start laying out our application's structure.

**Comment by jarhun88** [comment]
* What did you work on last iteration?

Team formation and discussion of team expectations, project requirements. Finalized team project proposal and created rough mockups of designs. 

* What were any major issues/challenges you ran into?

Creating and agreeing on an optimal design that we can implement. Still an ongoing issue to come up with better designs.

* What do you plan to work on for this coming iteration?

Create a solid design base that we can refer to when developing the UI. Creating a initial Front End of our website, division of tasks between teammates. 

CSID: h8u0b

**Comment by siddhero97** [comment]
- What did you work on the last iteration?

Firstly, we set laid out clearly our expectations for future collaborations; meeting times, standards of communication and code of conduct. Furthermore, we created designed prototypes for our designs. In addition, we discussed our requirements and expectations for the project.  

- What were any major issues/challenges you ran into?

Our designs weren't thorough. They will be refined through Figma. We will understand the more concrete aspects of our design as we implement the page and understand what's truly possible.

- What do you plan to work on for this coming iteration?

I believe our design wasn't hashed out enough. Henceforth, we will use Figma, in order to develop, a more refined illustration. Figma will also allow us to design more dynamic, which will allow us to easily adapt as the TA provides us with feedback. I would either work on the Login Page or the initial page with all of the products for a particular user. 

Student Number: 35169151
CSID: w7h0b

**Comment by siddhero97** [comment]
What did you work on the last iteration?
I worked on the Navbar and the title component. 

What were any major issues/challenges you ran into?
We had trouble collaborating with each other and managing pull requests. We also had time-management issues which came unclear managing. At times, some members had to redo another person's component. This made most issues double-worked on, which was very efficient. 

What do you plan to work on for this coming iteration?
We want to add the Redux functionality which includes al the actions. We will also add a better authentication system. 
StudentNumber: 35169151
CSID: w7h0b

**Comment by KwanLam17** [comment]
* What did you work on last iteration?

Discussed and planned our project task requirements, expectations. Created mock designs and prototypes of our application. Set expectations for future collaboration such as meeting times and standards of communication.

* What were any major issues/challenges you ran into?

Team communication, lack of it. We addressed this today after the workshop, so we will see how it goes and continue to improve.

* What do you plan to work on for this coming iteration?

1. Setup structure for redux
2. Add eslint rules
3. Add redux state for `item`
4. Add item details functionality

CSID: e6e8

**Comment by vincentchiang1** [comment]
What did you work on last iteration?

- Discussed and planned our project tasks. Created more mocks and prototypes. Implemented Login page UI.

What were any major issues/challenges you ran into?

- Team communication, lack of it. We addressed this today after the workshop, so we will see how it goes and continue to improve.

What do you plan to work on for this coming iteration?

- Add redux state for user

CSID: m9y0b

**Comment by jarhun88** [comment]
What did you work on last iteration?

Discussed and planned our project tasks. Implemented the sidebar component.

What were any major issues/challenges you ran into?

Fleshing out team work guidelines and upholding. Decided on a pledge for a more efficient team workflow. 

What do you plan to work on for this coming iteration?

- Design a figma mock for the project. 
- Create login form.
 
CSID: h8u0b

**Comment by siddhero97** [comment]
What did you work on the last iteration?

Work on the app state and redirection.

What were any major issues/challenges you ran into?

I did too many commits. This made it hard to rebase. 
What do you plan to work on for this coming iteration?

-TBD
CSID: w7h0b
