### ISSUE TITLE
Scrum Update 3 

### ISSUE THREAD

**Issue by jarhun88** [siddhero97/CS436I-Memofy#46]
**User Story**

As an `Instructor or TA`,
I want to `be updated with what each member is working on/will work on`,
So that `I can gauge their individual contributions to the team`.

**Functional Requirements**

* Every member writes a scrum update "comment" below answering the following questions:
  * What did you work on last iteration?
  * What were any major issues/challenges you ran into?
  * What do you plan to work on for this coming iteration?
  * CSID

**Comment by siddhero97** [comment]
What did you work on the last iteration?

Work on the app state and redirection.

What were any major issues/challenges you ran into?

I did too many commits. This made it hard to rebase.
What do you plan to work on for this coming iteration?

-TBD
CSID: w7h0b

**Comment by jarhun88** [comment]
* What did you work on last iteration?

Figma design file for UI and created a login modal component.

* What were any major issues/challenges you ran into?

Learning how to use figma. 

* What do you plan to work on for this coming iteration?

Creating a NodeJs server that is hooked up to mongoDB and calls POST/GET requests accordingly with login functionality. 

CSID: h8u0b

**Comment by vincentchiang1** [comment]
What did you work on last iteration?

- Add redux store and login/logout actions for user state, review teammates' PRs.

What were any major issues/challenges you ran into?

- Avoiding overlap and branching off other people's PRs

What do you plan to work on for this coming iteration?

- Creating a NodeJs server that is hooked up to mongoDB and calls POST/GET requests accordingly with login functionality. 

CSID: m9y0b

**Comment by KwanLam17** [comment]
What did you work on last iteration?
* Set up some initial eslint rules + automated build CI on GitHub
* Set up redux for our app
* Added Item state to our redux store

What were any major issues/challenges you ran into?
* Other priorities (final exams)

What do you plan to work on for this coming iteration?
* Create backend server to hook up with a database
* UI Improvements
* (Maybe) Add testing

CSID: e6e8
