### ISSUE TITLE
Create Icon 'search' UI for 'add new food item'

### ISSUE THREAD

**Issue by jarhun88** [siddhero97/CS436I-Memofy#72]
**User Story**

As a user,
I want to `be able to search and select an icon from an icon library that I want to use as the item's icon.'

**Functional Requirements**

* you can search for icons from the 'Add new food item' modal and select one
* you can see the icon on the ui for the added item.
* this data (whatever it is) successfully transfers to the db and persists when you reload page (aka you can still see the icon)

**Comment by KwanLam17** [comment]
https://www.iconfinder.com
