### ISSUE TITLE
Scrum Update 4

### ISSUE THREAD

**Issue by KwanLam17** [siddhero97/CS436I-Memofy#83]
**User Story**

As an `Instructor or TA`,
I want to `be updated with what each member is working on/will work on`,
So that `I can gauge their individual contributions to the team`.

**Functional Requirements**

* Every member writes a scrum update "comment" below answering the following questions:
  * What did you work on last iteration?
  * What were any major issues/challenges you ran into?
  * What do you plan to work on for this coming iteration?
  * CSID

**Comment by KwanLam17** [comment]
What did you work on last iteration?
* Set up backend architecture/application with example routes

What were any major issues/challenges you ran into?
* Fell ill for a week or so

What do you plan to work on for this coming iteration?
* Create User schema/routes
* Add more linting
* Profile page
* Create Fridge schema/routes
* UI Improvements
* (Maybe) Add testing

CSID: e6e8

**Comment by jarhun88** [comment]
What did you work on last iteration?
* Implement backend server routes for GET POST PUT DELETE for Item objects
* Implement client logic for DELETE POST for Item objects 
* Implement Landing page

What were any major issues/challenges you ran into?
* Implementing Redux Thunk

What do you plan to work on for this coming iteration?
* UI, Client logic, server logic for Filtering Items. 

CSID: h8u0b

**Comment by vincentchiang1** [comment]
What did you work on last iteration?

Implement backend server routes for GET POST PUT DELETE for Item objects
Implement client logic for GET Item 
Add MongoDB connection
Define Schemas for MongoDB objects

What were any major issues/challenges you ran into?

Implementing Redux Thunk
What do you plan to work on for this coming iteration?

Improve Add and Edit item functionality in front end
CSID: m9y0b

**Comment by siddhero97** [comment]
What did you work on last iteration?

Define Schemas for MongoDB objects

What were any major issues/challenges you ran into?

Adding redux thunk to backend.
What do you plan to work on for this coming iteration?

Add Profile Page and Add Authentication. 
CSID: w7h0b
