### ISSUE TITLE
Scrum Update 5

### ISSUE THREAD

**Issue by vincentchiang1** [siddhero97/CS436I-Memofy#99]
User Story

As an Instructor or TA,
I want to be updated with what each member is working on/will work on,
So that I can gauge their individual contributions to the team.

Functional Requirements

Every member writes a scrum update "comment" below answering the following questions:
What did you work on last iteration?
What were any major issues/challenges you ran into?
What do you plan to work on for this coming iteration?
CSID

**Comment by vincentchiang1** [comment]
What did you work on last iteration?

Implement fully functional add item with new UI.
Work on being being able to edit an item's fields and new UI.

What were any major issues/challenges you ran into?

Designing an optimal UI

What do you plan to work on for this coming iteration?

Completing edit item functionality, discussing remaining features to complete for the end of the project, creating documentation, creating a powerpoint, preparing for presentation


CSID: m9y0b

**Comment by jarhun88** [comment]
What did you work on last iteration?
- Designed the initial Fridge schema and setup server routes. 
- Created fridge icon designs on figma and on client side.
- Implemented redux to call for active user/fridge and see items. 
What were any major issues/challenges you ran into?
- Actually writing code for the ui for the fridge icons. 
- redux calls are difficult to implement
What do you plan to work on for this coming iteration?
- cleanup fridge icon ui
- implement filter by categories
- presentation

CSID h8u0b

**Comment by KwanLam17** [comment]
What did you work on last iteration?

* Refactor backend with new model(s) and included logic to fully-support our endpoints
* Add jwt token authentication and protected routes
* Refactor project structure and deploy to heroku

What were any major issues/challenges you ran into?

Deploying to heroku was a hefty and time-consuming task (lots of trail and error).

What do you plan to work on for this coming iteration?

* Finish refactoring to add in our new client functionalities (refer to point #1 in "What did you work on last iteration?")
* Add IconFinder API to support our item icons
* Add Search functionality for items
* Refactor the Navbar
* Other standard requirement implementations


CSID: e6e8

**Comment by siddhero97** [comment]
What did you work on the last iteration?
Worked on the profile page

What were any major issues/challenges you ran into?

Managing productivity and learning about Shopify's features
What do you plan to work on for this coming iteration?

Creating presentation. Creating documentation. Finishing up personal profile


CSID: w70b
